<?php

if (!defined('USER_DEFAULT_IMG_PATH')) define('USER_DEFAULT_IMG_PATH', '/assets/images/default-user.jpg');
if (!defined('ITEM_DEFAULT_IMG_PATH')) define('ITEM_DEFAULT_IMG_PATH', '/assets/images/default-item.svg');

if (!defined('USER_ROLES')) define('USER_ROLES', [
    'freelancer', 'employer'
]);
if (!defined('FREELANCER')) define('FREELANCER', 'freelancer');
if (!defined('EMPLOYER')) define('EMPLOYER', 'employer');

if (!defined('PROFILE_STATUS')) define('PROFILE_STATUS', [
    'active', 'inactive'
]);
if (!defined('ACTIVE')) define('ACTIVE', 'active');
if (!defined('INACTIVE')) define('INACTIVE', 'inactive');

if (!defined('JOB_STATUS')) define('JOB_STATUS', [
    'active', 'expired'
]);
if (!defined('EXPIRED')) define('EXPIRED', 'expired');

if (!defined('ACTIVEJOB_STATUS')) define('ACTIVEJOB_STATUS', [
    'ongoing', 'ended'
]);

if (!defined('ONGOING')) define('ONGOING', 'ongoing');
if (!defined('ENDED')) define('ENDED', 'ended');

if (!defined('ACTIVITY_STATUS')) define('ACTIVITY_STATUS', [
    'delivered', 'failed'
]);
if (!defined('DELIVERED')) define('DELIVERED', 'delivered');
if (!defined('FAILED')) define('FAILED', 'failed');

if (!defined('APPLICANT_STATUS')) define('APPLICANT_STATUS', [
    'pending', 'confirm', 'reject'
]);
if (!defined('PENDING')) define('PENDING', 'pending');
if (!defined('CONFIRM')) define('CONFIRM', 'confirm');
if (!defined('REJECT')) define('REJECT', 'reject');

if (!defined('EXPERIENCE_LEVEL')) define('EXPERIENCE_LEVEL', [
    'Internship', 'Entry Level', 'Associate', 'Mid-Senior Level', 'Director', 'Excutive'
]);
if (!defined('EDUCATION_LEVEL')) define('EDUCATION_LEVEL', [
    'Graduated', 'Undergraduated', 'Diploma', 'Cerificate'
]);
if (!defined('TEAM_SIZE')) define('TEAM_SIZE', [
    '0 - 5', '5 - 10', '10 - 20', '20 - 50', '50 - more'
]);

if (!defined('ACTIVITY_TYPE')) define('ACTIVITY_TYPE', [
    'add', 'modify', 'remove'
]);
if (!defined('ADD')) define('ADD', 'add');
if (!defined('MODIFY')) define('MODIFY', 'modify');
if (!defined('REMOVE')) define('REMOVE', 'remove');

if (!defined('COUNTRY_LIST')) define('COUNTRY_LIST', [
    'af' => 'Afghanistan',
    'ax' => 'Aland Islands',
    'al' => 'Albania',
    'dz' => 'Algeria',
    'as' => 'American Samoa',
    'ad' => 'Andorra',
    'ao' => 'Angola',
    'ai' => 'Anguilla',
    'aq' => 'Antarctica',
    'ag' => 'Antigua and Barbuda',
    'ar' => 'Argentina',
    'am' => 'Armenia',
    'aw' => 'Aruba',
    'au' => 'Australia',
    'at' => 'Austria',
    'az' => 'Azerbaijan',
    'bs' => 'Bahamas',
    'bh' => 'Bahrain',
    'bd' => 'Bangladesh',
    'bb' => 'Barbados',
    'by' => 'Belarus',
    'be' => 'Belgium',
    'bz' => 'Belize',
    'bj' => 'Benin',
    'bm' => 'Bermuda',
    'bt' => 'Bhutan',
    'bo' => 'Bolivia',
    'bq' => 'Bonaire, Sint Eustatius and Saba',
    'ba' => 'Bosnia and Herzegovina',
    'bw' => 'Botswana',
    'bv' => 'Bouvet Island',
    'br' => 'Brazil',
    'io' => 'British Indian Ocean Territory',
    'bn' => 'Brunei Darussalam',
    'bg' => 'Bulgaria',
    'bf' => 'Burkina Faso',
    'bi' => 'Burundi',
    'cv' => 'Cabo Verde',
    'kh' => 'Cambodia',
    'cm' => 'Cameroon',
    'ca' => 'Canada',
    'ky' => 'Cayman Islands',
    'cf' => 'Central African Republic',
    'td' => 'Chad',
    'cl' => 'Chile',
    'cn' => 'China',
    'cx' => 'Christmas Island',
    'cc' => 'Cocos (Keeling) Islands',
    'co' => 'Colombia',
    'km' => 'Comoros',
    'ck' => 'Cook Islands',
    'cr' => 'Costa Rica',
    'hr' => 'Croatia',
    'cu' => 'Cuba',
    'cw' => 'Curaçao',
    'cy' => 'Cyprus',
    'cz' => 'Czech Republic',
    'ci' => "Côte d'Ivoire",
    'cd' => 'Democratic Republic of the Congo',
    'dk' => 'Denmark',
    'dj' => 'Djibouti',
    'dm' => 'Dominica',
    'do' => 'Dominican Republic',
    'ec' => 'Ecuador',
    'eg' => 'Egypt',
    'sv' => 'El Salvador',
    'gq' => 'Equatorial Guinea',
    'er' => 'Eritrea',
    'ee' => 'Estonia',
    'sz' => 'Eswatini',
    'et' => 'Ethiopia',
    'fk' => 'Falkland Islands',
    'fo' => 'Faroe Islands',
    'fm' => 'Federated States of Micronesia',
    'fj' => 'Fiji',
    'fi' => 'Finland',
    'fr' => 'France',
    'gf' => 'French Guiana',
    'pf' => 'French Polynesia',
    'tf' => 'French Southern Territories',
    'ga' => 'Gabon',
    'gm' => 'Gambia',
    'ge' => 'Georgia',
    'de' => 'Germany',
    'gh' => 'Ghana',
    'gi' => 'Gibraltar',
    'gr' => 'Greece',
    'gl' => 'Greenland',
    'gd' => 'Grenada',
    'gp' => 'Guadeloupe',
    'gu' => 'Guam',
    'gt' => 'Guatemala',
    'gg' => 'Guernsey',
    'gn' => 'Guinea',
    'gw' => 'Guinea-Bissau',
    'gy' => 'Guyana',
    'ht' => 'Haiti',
    'hm' => 'Heard Island and McDonald Islands',
    'va' => 'Holy See',
    'hn' => 'Honduras',
    'hk' => 'Hong Kong',
    'hu' => 'Hungary',
    'is' => 'Iceland',
    'in' => 'India',
    'id' => 'Indonesia',
    'ir' => 'Iran',
    'iq' => 'Iraq',
    'ie' => 'Ireland',
    'im' => 'Isle of Man',
    'il' => 'Israel',
    'it' => 'Italy',
    'jm' => 'Jamaica',
    'jp' => 'Japan',
    'je' => 'Jersey',
    'jo' => 'Jordan',
    'kz' => 'Kazakhstan',
    'ke' => 'Kenya',
    'ki' => 'Kiribati',
    'kw' => 'Kuwait',
    'kg' => 'Kyrgyzstan',
    'la' => 'Laos',
    'lv' => 'Latvia',
    'lb' => 'Lebanon',
    'ls' => 'Lesotho',
    'lr' => 'Liberia',
    'ly' => 'Libya',
    'li' => 'Liechtenstein',
    'lt' => 'Lithuania',
    'lu' => 'Luxembourg',
    'mo' => 'Macau',
    'mg' => 'Madagascar',
    'mw' => 'Malawi',
    'my' => 'Malaysia',
    'mv' => 'Maldives',
    'ml' => 'Mali',
    'mt' => 'Malta',
    'mh' => 'Marshall Islands',
    'mq' => 'Martinique',
    'mr' => 'Mauritania',
    'mu' => 'Mauritius',
    'yt' => 'Mayotte',
    'mx' => 'Mexico',
    'md' => 'Moldova',
    'mc' => 'Monaco',
    'mn' => 'Mongolia',
    'me' => 'Montenegro',
    'ms' => 'Montserrat',
    'ma' => 'Morocco',
    'mz' => 'Mozambique',
    'mm' => 'Myanmar',
    'na' => 'Namibia',
    'nr' => 'Nauru',
    'np' => 'Nepal',
    'nl' => 'Netherlands',
    'nc' => 'New Caledonia',
    'nz' => 'New Zealand',
    'ni' => 'Nicaragua',
    'ne' => 'Niger',
    'ng' => 'Nigeria',
    'nu' => 'Niue',
    'nf' => 'Norfolk Island',
    'kp' => 'North Korea',
    'mk' => 'North Macedonia',
    'mp' => 'Northern Mariana Islands',
    'no' => 'Norway',
    'om' => 'Oman',
    'pk' => 'Pakistan',
    'pw' => 'Palau',
    'pa' => 'Panama',
    'pg' => 'Papua New Guinea',
    'py' => 'Paraguay',
    'pe' => 'Peru',
    'ph' => 'Philippines',
    'pn' => 'Pitcairn',
    'pl' => 'Poland',
    'pt' => 'Portugal',
    'pr' => 'Puerto Rico',
    'qa' => 'Qatar',
    'cg' => 'Republic of the Congo',
    'ro' => 'Romania',
    'ru' => 'Russia',
    'rw' => 'Rwanda',
    're' => 'Réunion',
    'bl' => 'Saint Barthélemy',
    'sh' => 'Saint Helena, Ascension and Tristan da Cunha',
    'kn' => 'Saint Kitts and Nevis',
    'lc' => 'Saint Lucia',
    'mf' => 'Saint Martin',
    'pm' => 'Saint Pierre and Miquelon',
    'vc' => 'Saint Vincent and the Grenadines',
    'ws' => 'Samoa',
    'sm' => 'San Marino',
    'st' => 'Sao Tome and Principe',
    'sa' => 'Saudi Arabia',
    'sn' => 'Senegal',
    'rs' => 'Serbia',
    'sc' => 'Seychelles',
    'sl' => 'Sierra Leone',
    'sg' => 'Singapore',
    'sx' => 'Sint Maarten',
    'sk' => 'Slovakia',
    'si' => 'Slovenia',
    'sb' => 'Solomon Islands',
    'so' => 'Somalia',
    'za' => 'South Africa',
    'gs' => 'South Georgia and the South Sandwich Islands',
    'kr' => 'South Korea',
    'ss' => 'South Sudan',
    'es' => 'Spain',
    'lk' => 'Sri Lanka',
    'ps' => 'State of Palestine',
    'sd' => 'Sudan',
    'sr' => 'Suriname',
    'sj' => 'Svalbard and Jan Mayen',
    'se' => 'Sweden',
    'ch' => 'Switzerland',
    'sy' => 'Syria',
    'tw' => 'Taiwan',
    'tj' => 'Tajikistan',
    'tz' => 'Tanzania',
    'th' => 'Thailand',
    'tl' => 'Timor-Leste',
    'tg' => 'Togo',
    'tk' => 'Tokelau',
    'to' => 'Tonga',
    'tt' => 'Trinidad and Tobago',
    'tn' => 'Tunisia',
    'tm' => 'Turkmenistan',
    'tc' => 'Turks and Caicos Islands',
    'tv' => 'Tuvalu',
    'tr' => 'Türkiye',
    'ug' => 'Uganda',
    'ua' => 'Ukraine',
    'ae' => 'United Arab Emirates',
    'gb' => 'United Kingdom',
    'um' => 'United States Minor Outlying Islands',
    'us' => 'United States of America',
    'uy' => 'Uruguay',
    'uz' => 'Uzbekistan',
    'vu' => 'Vanuatu',
    've' => 'Venezuela',
    'vn' => 'Vietnam',
    'vg' => 'Virgin Islands (British)',
    'vi' => 'Virgin Islands (U.S.)',
    'wf' => 'Wallis and Futuna',
    'eh' => 'Western Sahara',
    'ye' => 'Yemen',
    'zm' => 'Zambia',
    'zw' => 'Zimbabwe',
]);

if (!defined('ICON_LIST')) define('ICON_LIST', [
    "<span class='flaticon-notebook'></span>",
    "<span class='flaticon-edit'></span>",
    "<span class='flaticon-placeholder'></span>",
    "<span class='flaticon-paper-plane'></span>",
    "<span class='flaticon-user'></span>",
    "<span class='flaticon-unlink'></span>",
    "<span class='flaticon-search'></span>",
    "<span class='flaticon-drop'></span>",
    "<span class='flaticon-christmas-tree'></span>",
    "<span class='flaticon-plus'></span>",
    "<span class='flaticon-battery'></span>",
    "<span class='flaticon-target'></span>",
    "<span class='flaticon-first-aid-kit'></span>",
    "<span class='flaticon-tablet'></span>",
    "<span class='flaticon-dustbin'></span>",
    "<span class='flaticon-telegram-logo'></span>",
    "<span class='flaticon-4-square-shapes'></span>",
    "<span class='flaticon-speech-bubble-and-three-dots'></span>",
    "<span class='flaticon-man'></span>",
    "<span class='flaticon-tree-of-love'></span>",
    "<span class='flaticon-play-button'></span>",
    "<span class='flaticon-royal-crown-of-elegant-vintage-design'></span>",
    "<span class='flaticon-desktop-computer-with-magnifying-lens-focusing-on-data'></span>",
    "<span class='flaticon-test-tube-flask-and-drop-of-blood'></span>",
    "<span class='flaticon-stocks-graphic-on-laptop-monitor'></span>",
    "<span class='flaticon-attachment'></span>",
    "<span class='flaticon-transport'></span>",
    "<span class='flaticon-recycle-triangle-of-three-arrows-outlines'></span>",
    "<span class='flaticon-arrows'></span>",
    "<span class='flaticon-snowflake'></span>",
    "<span class='flaticon-clock'></span>",
    "<span class='flaticon-find-in-folder'></span>",
    "<span class='flaticon-smartphone'></span>",
    "<span class='flaticon-arrow-pointing-to-right'></span>",
    "<span class='flaticon-gas-pump'></span>",
    "<span class='flaticon-house-silhouette'></span>",
    "<span class='flaticon-arrows-1'></span>",
    "<span class='flaticon-floor'></span>",
    "<span class='flaticon-exercise'></span>",
    "<span class='flaticon-love-planet'></span>",
    "<span class='flaticon-workers'></span>",
    "<span class='flaticon-open-magazine'></span>",
    "<span class='flaticon-confirm-schedule'></span>",
    "<span class='flaticon-star'></span>",
    "<span class='flaticon-order'></span>",
    "<span class='flaticon-key'></span>",
    "<span class='flaticon-medical'></span>",
    "<span class='flaticon-smartphone-1'></span>",
    "<span class='flaticon-plug'></span>",
    "<span class='flaticon-arrows-2'></span>",
    "<span class='flaticon-arrows-3'></span>",
    "<span class='flaticon-money-bag'></span>",
    "<span class='flaticon-next'></span>",
    "<span class='flaticon-back'></span>",
    "<span class='flaticon-reload'></span>",
    "<span class='flaticon-headphones'></span>",
    "<span class='flaticon-signs'></span>",
    "<span class='flaticon-diamond'></span>",
    "<span class='flaticon-chat'></span>",
    "<span class='flaticon-phone'></span>",
    "<span class='flaticon-down-chevron'></span>",
    "<span class='flaticon-up-chevron'></span>",
    "<span class='flaticon-stairs'></span>",
    "<span class='flaticon-music-player'></span>",
    "<span class='flaticon-play-button-1'></span>",
    "<span class='flaticon-speaker'></span>",
    "<span class='flaticon-menu'></span>",
    "<span class='flaticon-share'></span>",
    "<span class='flaticon-map'></span>",
    "<span class='flaticon-hourglass'></span>",
    "<span class='flaticon-layers'></span>",
    "<span class='flaticon-home'></span>",
    "<span class='flaticon-handshake'></span>",
    "<span class='flaticon-time'></span>",
    "<span class='flaticon-worldwide'></span>",
    "<span class='flaticon-board'></span>",
    "<span class='flaticon-twitter'></span>",
    "<span class='flaticon-smartphone-2'></span>",
    "<span class='flaticon-mobile'></span>",
    "<span class='flaticon-maps-and-flags'></span>",
    "<span class='flaticon-add'></span>",
    "<span class='flaticon-substract'></span>",
    "<span class='flaticon-phone-call'></span>",
    "<span class='flaticon-monitor'></span>",
    "<span class='flaticon-menu-1'></span>",
    "<span class='flaticon-cancel'></span>",
    "<span class='flaticon-24-hours'></span>",
    "<span class='flaticon-t-shirt-outline'></span>",
    "<span class='flaticon-folder-outline'></span>",
    "<span class='flaticon-quote'></span>",
    "<span class='flaticon-play-button-2'></span>",
    "<span class='flaticon-right-quotation-sign'></span>",
    "<span class='flaticon-up-arrow'></span>",
    "<span class='flaticon-open-mail-interface-symbol'></span>",
    "<span class='flaticon-menu-button'></span>",
    "<span class='flaticon-smartphone-3'></span>",
    "<span class='flaticon-add-1'></span>",
    "<span class='flaticon-play-button-3'></span>",
    "<span class='flaticon-play-button-4'></span>",
    "<span class='flaticon-support'></span>",
    "<span class='flaticon-close'></span>",
    "<span class='flaticon-heart-1'></span>",
    "<span class='flaticon-renewable'></span>",
    "<span class='flaticon-bar-chart'></span>",
    "<span class='flaticon-profit'></span>",
    "<span class='flaticon-settings'></span>",
    "<span class='flaticon-confirm'></span>",
    "<span class='flaticon-edit-1'></span>",
    "<span class='flaticon-share-1'></span>",
    "<span class='flaticon-decreasing'></span>",
    "<span class='flaticon-graph'></span>",
    "<span class='flaticon-multi-tab'></span>",
    "<span class='flaticon-graph-1'></span>",
    "<span class='flaticon-graph-2'></span>",
    "<span class='flaticon-tick'></span>",
    "<span class='flaticon-pin'></span>",
    "<span class='flaticon-alarm-clock'></span>",
    "<span class='flaticon-close-1'></span>",
    "<span class='flaticon-settings-1'></span>",
    "<span class='flaticon-telephone'></span>",
    "<span class='flaticon-home-1'></span>",
    "<span class='flaticon-search-1'></span>",
    "<span class='flaticon-notification'></span>",
    "<span class='flaticon-attachment-1'></span>",
    "<span class='flaticon-down-arrow'></span>",
    "<span class='flaticon-tv'></span>",
    "<span class='flaticon-phone-receiver'></span>",
    "<span class='flaticon-next-1'></span>",
    "<span class='flaticon-back-1'></span>",
    "<span class='flaticon-clock-1'></span>",
    "<span class='flaticon-email'></span>",
    "<span class='flaticon-email-1'></span>",
    "<span class='flaticon-engineer'></span>",
    "<span class='flaticon-cog'></span>",
    "<span class='flaticon-cog-1'></span>",
    "<span class='flaticon-call'></span>",
    "<span class='flaticon-call-1'></span>",
    "<span class='flaticon-email-2'></span>",
    "<span class='flaticon-shopping-bag'></span>",
    "<span class='flaticon-clock-2'></span>",
    "<span class='flaticon-custom'></span>",
    "<span class='flaticon-settings-2'></span>",
    "<span class='flaticon-monitor-1'></span>",
    "<span class='flaticon-stats'></span>",
    "<span class='flaticon-monitor-2'></span>",
    "<span class='flaticon-bars'></span>",
    "<span class='flaticon-bar-chart-1'></span>",
    "<span class='flaticon-bars-1'></span>",
    "<span class='flaticon-camera'></span>",
    "<span class='flaticon-camera-1'></span>",
    "<span class='flaticon-camera-2'></span>",
    "<span class='flaticon-dslr-camera'></span>",
    "<span class='flaticon-tower'></span>",
    "<span class='flaticon-technical-support'></span>",
    "<span class='flaticon-maintenance'></span>",
    "<span class='flaticon-production'></span>",
    "<span class='flaticon-3d-printer'></span>",
    "<span class='flaticon-gift'></span>",
    "<span class='flaticon-winner'></span>",
    "<span class='flaticon-diploma'></span>",
    "<span class='flaticon-diploma-1'></span>",
    "<span class='flaticon-medal'></span>",
    "<span class='flaticon-title'></span>",
    "<span class='flaticon-certificate'></span>",
    "<span class='flaticon-meeting-point'></span>",
    "<span class='flaticon-pin-1'></span>",
    "<span class='flaticon-email-3'></span>",
    "<span class='flaticon-call-2'></span>",
    "<span class='flaticon-telephone-1'></span>",
    "<span class='flaticon-teacher'></span>",
    "<span class='flaticon-support-2'></span>",
    "<span class='flaticon-design-tool'></span>",
    "<span class='flaticon-success'></span>",
    "<span class='flaticon-startup'></span>",
    "<span class='flaticon-creativity'></span>",
    "<span class='flaticon-creativity-1'></span>",
    "<span class='flaticon-puzzle'></span>",
    "<span class='flaticon-vector-1'></span>",
    "<span class='flaticon-brainstorm'></span>",
    "<span class='flaticon-pencil'></span>",
    "<span class='flaticon-typography'></span>",
    "<span class='flaticon-lightbulb'></span>",
    "<span class='flaticon-cancel-1'></span>",
    "<span class='flaticon-dislike'></span>",
    "<span class='flaticon-paper-plane-1'></span>",
    "<span class='flaticon-mail'></span>",
    "<span class='flaticon-call-3'></span>",
    "<span class='flaticon-shopping-cart'></span>",
    "<span class='flaticon-shopping-cart-1'></span>",
    "<span class='flaticon-heart'></span>",
    "<span class='flaticon-compare'></span>",
    "<span class='flaticon-user-1'></span>",
    "<span class='flaticon-loupe'></span>",
    "<span class='flaticon-paper-clip'></span>",
    "<span class='flaticon-shield'></span>",
    "<span class='flaticon-diamond-2'></span>",
    "<span class='flaticon-checked'></span>",
    "<span class='flaticon-right'></span>",
    "<span class='flaticon-left'></span>",
    "<span class='flaticon-padlock'></span>",
    "<span class='flaticon-starred'></span>",
    "<span class='flaticon-star-1'></span>",
    "<span class='flaticon-grid'></span>",
    "<span class='flaticon-option'></span>",
    "<span class='flaticon-sort'></span>",
    "<span class='flaticon-delete'></span>",
    "<span class='flaticon-envelope'></span>",
    "<span class='flaticon-quote-1'></span>",
    "<span class='flaticon-briefcase'></span>",
    "<span class='flaticon-file'></span>",
    "<span class='flaticon-money-1'></span>",
    "<span class='flaticon-promotion'></span>",
    "<span class='flaticon-megaphone'></span>",
    "<span class='flaticon-vector'></span>",
    "<span class='flaticon-web-programming'></span>",
    "<span class='flaticon-rocket-ship'></span>",
    "<span class='flaticon-headhunting'></span>",
    "<span class='flaticon-approved'></span>",
    "<span class='flaticon-support-1'></span>",
    "<span class='flaticon-first-aid-kit-1'></span>",
    "<span class='flaticon-car'></span>",
    "<span class='flaticon-compact'></span>",
    "<span class='flaticon-map-locator'></span>",
    "<span class='flaticon-clock-3'></span>",
    "<span class='flaticon-money'></span>",
    "<span class='flaticon-money-2'></span>",
    "<span class='flaticon-bookmark'></span>",
    "<span class='flaticon-search-2'></span>",
    "<span class='flaticon-search-3'></span>",
]);
